version: '3.8'
services:
  movies:
    image: sereddydevops/paytmmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: sereddydevops/paytmbills:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: sereddydevops/paytmdth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: sereddydevops/paytmrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
